class ModelCountry {
  String name;
  String flag;
  String code;
  String iso;
  String iso_code;
  String currency;
  String currency_symbol;
  String time_zone;
  double latitude;
  double longitude;

  ModelCountry({
    required this.name,
    required this.flag,
    required this.code,
    required this.iso,
    required this.iso_code,
    required this.currency,
    required this.currency_symbol,
    required this.time_zone,
    required this.latitude,
    required this.longitude,
  });

  static List<ModelCountry> countries = [
    ModelCountry(
        name: "Pakistan",
        flag: "🇵🇰",
        code: "+92",
        iso: "PAK",
        iso_code: "PK",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),

    ModelCountry(
        name: "Afghanistan",
        code: "+93",
        flag: "🇦🇫",
        iso: "AFG",
        iso_code: "AF",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Albania",
        code: "+355",
        flag: "🇦🇱",
        iso: "ALB",
        iso_code: "AL",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Algeria",
        code: "+213",
        flag: "🇩🇿",
        iso: "DZA",
        iso_code: "DZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Andorra",
        code: "+376",
        flag: "🇦🇩",
        iso: "AND",
        iso_code: "AD",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Antarctica",
        code: "+672",
        flag: "🇦🇶",
        iso: "ATA",
        iso_code: "AQ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Angola",
        code: "+244",
        flag: "🇦🇴",
        iso: "AGO",
        iso_code: "AO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Anguilla",
        code: "+1-264",
        flag: "🇦🇮",
        iso: "AIA",
        iso_code: "AI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Antigua and Barbuda",
        code: "+1-268",
        flag: "🇦🇬",
        iso: "ATG",
        iso_code: "AG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Argentina",
        code: "+54",
        flag: "🇦🇷",
        iso: "ARG",
        iso_code: "AR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Armenia",
        code: "+374",
        flag: "🇦🇲",
        iso: "ARM",
        iso_code: "AM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Aruba",
        code: "+297",
        flag: "🇦🇼",
        iso: "ABW",
        iso_code: "AW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Australia",
        code: "+61",
        flag: "🇦🇺",
        iso: "AUS",
        iso_code: "AU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Austria",
        code: "+43",
        flag: "🇦🇹",
        iso: "AUT",
        iso_code: "AT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Azerbaijan ",
        code: "+994",
        flag: "🇦🇿",
        iso: "AZE",
        iso_code: "AZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bahamas",
        code: "+1-242",
        flag: "🇧🇸",
        iso: "BHS",
        iso_code: "BS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bahrain",
        code: "+973",
        flag: "🇧🇭",
        iso: "BHR",
        iso_code: "BH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bangladesh",
        code: "+880",
        flag: "🇧🇩",
        iso: "BGD",
        iso_code: "BD",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Barbados",
        code: "+1-246",
        flag: "🇧🇧",
        iso: "BRB",
        iso_code: "BB",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Belarus",
        code: "+375",
        flag: "🇧🇾",
        iso: "BLR",
        iso_code: "BY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Belgium",
        code: "+32",
        flag: "🇧🇪",
        iso: "BEL",
        iso_code: "BE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Belize",
        code: "+501",
        flag: "🇧🇿",
        iso: "BLZ",
        iso_code: "BZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Benin",
        code: "+229",
        flag: "🇧🇯",
        iso: "BEN",
        iso_code: "BJ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bhutan",
        code: "+975",
        flag: "🇧🇹",
        iso: "BTN",
        iso_code: "BT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bolivia",
        code: "+591",
        flag: "🇧🇴",
        iso: "BOL",
        iso_code: "BO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bosnia and Herzegovina",
        code: "+387",
        flag: "🇧🇦",
        iso: "BIH",
        iso_code: "BA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Botswana",
        code: "+267",
        flag: "🇧🇼",
        iso: "BWA",
        iso_code: "BW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Brazil",
        code: "+55",
        flag: "🇧🇷",
        iso: "BRA",
        iso_code: "BR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Brunei",
        code: "+673",
        flag: "🇧🇳",
        iso: "BRN",
        iso_code: "BN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Bulgaria",
        code: "+359",
        flag: "🇧🇬",
        iso: "BGR",
        iso_code: "BG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Burkina Faso",
        code: "+226",
        flag: "🇧🇫",
        iso: "BFA",
        iso_code: "BF",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Burundi ",
        code: "+257",
        flag: "🇧🇮",
        iso: "BDI",
        iso_code: "BI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Cape Verde",
        code: "+238",
        flag: "🇨🇻",
        iso: "CPV",
        iso_code: "CV",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Cambodia",
        code: "+855",
        flag: "🇰🇭",
        iso: "KHM",
        iso_code: "KH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Cameroon",
        code: "+237",
        flag: "🇨🇲",
        iso: "CMR",
        iso_code: "CM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Canada",
        code: "+1",
        flag: "🇨🇦",
        iso: "CAN",
        iso_code: "CA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Central African Republic",
        code: "+236",
        flag: "🇨🇫",
        iso: "CAF",
        iso_code: "CF",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Chad",
        code: "+235",
        flag: "🇹🇩",
        iso: "TCD",
        iso_code: "TD",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Chile",
        code: "+56",
        flag: "🇨🇱",
        iso: "CHL",
        iso_code: "CL",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "China",
        code: "+86",
        flag: "🇨🇳",
        iso: "CHN",
        iso_code: "CN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Colombia",
        code: "+57",
        flag: "🇨🇴",
        iso: "COL",
        iso_code: "CO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Comoros",
        code: "+269",
        flag: "🇰🇲",
        iso: "COM",
        iso_code: "KM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Congo",
        code: "+242",
        flag: "🇨🇬",
        iso: "COG",
        iso_code: "CG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Costa Rica",
        code: "+506",
        flag: "🇨🇷",
        iso: "CRI",
        iso_code: "CR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Côte d’Ivoire",
        code: "+225",
        flag: "🇨🇮",
        iso: "CIV",
        iso_code: "CI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Croatia",
        code: "+385",
        flag: "🇭🇷",
        iso: "HRV",
        iso_code: "HR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Cuba",
        code: "+53",
        flag: "🇨🇺",
        iso: "CUB",
        iso_code: "CU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Cyprus",
        code: "+357",
        flag: "🇨🇾",
        iso: "CYP",
        iso_code: "CY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Denmark",
        code: "+45",
        flag: "🇩🇰",
        iso: "DNK",
        iso_code: "DK",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Djibouti",
        code: "+253",
        flag: "🇩🇯",
        iso: "DJI",
        iso_code: "DJ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Dominica",
        code: "+1-767",
        flag: "🇩🇲",
        iso: "DMA",
        iso_code: "DM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Dominican Republic ",
        code: "+1-809, 1-829, 1-849",
        flag: "🇩🇴",
        iso: "DOM",
        iso_code: "DO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Ecuador",
        code: "+593",
        flag: "🇪🇨",
        iso: "ECU",
        iso_code: "EC",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Egypt",
        code: "+20",
        flag: "🇪🇬",
        iso: "EGY",
        iso_code: "EG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "El Salvador",
        code: "+503",
        flag: "🇸🇻",
        iso: "SLV",
        iso_code: "SV",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Equatorial Guinea",
        code: "+240",
        flag: "🇬🇶",
        iso: "GNQ",
        iso_code: "GQ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Eritrea",
        code: "+291",
        flag: "🇪🇷",
        iso: "ERI",
        iso_code: "ER",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Estonia",
        code: "+372",
        flag: "🇪🇪",
        iso: "EST",
        iso_code: "EE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Eswatini",
        code: "+268",
        flag: "🇸🇿",
        iso: "SWZ",
        iso_code: "SZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Ethiopia ",
        code: "+251",
        flag: "🇪🇹",
        iso: "ETH",
        iso_code: "ET",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Fiji",
        code: "+679",
        flag: "🇫🇯",
        iso: "FJI",
        iso_code: "FJ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Finland",
        code: "+358",
        flag: "🇫🇮",
        iso: "FIN",
        iso_code: "FI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "France ",
        code: "+33",
        flag: "🇫🇷",
        iso: "FRA",
        iso_code: "FR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Gabon",
        code: "+241",
        flag: "🇬🇦",
        iso: "GAB",
        iso_code: "GA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Gambia",
        code: "+220",
        flag: "🇬🇲",
        iso: "GMB",
        iso_code: "GM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Georgia",
        code: "+995",
        flag: "🇬🇪",
        iso: "GEO",
        iso_code: "GE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Germany",
        code: "+49",
        flag: "🇩🇪",
        iso: "DEU",
        iso_code: "DE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Ghana",
        code: "+233",
        flag: "🇬🇭",
        iso: "GHA",
        iso_code: "GH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Greece",
        code: "+30",
        flag: "🇬🇷",
        iso: "GRC",
        iso_code: "GR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Grenada",
        code: "+1-473",
        flag: "🇬🇩",
        iso: "GRD",
        iso_code: "GD",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Guatemala",
        code: "+502",
        flag: "🇬🇹",
        iso: "GTM",
        iso_code: "GT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Guinea",
        code: "+224",
        flag: "🇬🇳",
        iso: "GIN",
        iso_code: "GN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Guinea-Bissau",
        code: "+245",
        flag: "🇬🇼",
        iso: "GNB",
        iso_code: "GW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Guyana",
        code: "+592",
        flag: "🇬🇾",
        iso: "GUY",
        iso_code: "GY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Haiti",
        code: "+509",
        flag: "🇭🇹",
        iso: "HTI",
        iso_code: "HT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Honduras",
        code: "+504",
        flag: "🇭🇳",
        iso: "HND",
        iso_code: "HN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Hungary",
        code: "+36",
        flag: "🇭🇺",
        iso: "HUN",
        iso_code: "HU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Iceland",
        code: "+354",
        flag: "🇮🇸",
        iso: "ISL",
        iso_code: "IS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "India",
        code: "+91",
        flag: "🇮🇳",
        iso: "IND",
        iso_code: "IN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Indonesia",
        code: "+62",
        flag: "🇮🇩",
        iso: "IDN",
        iso_code: "ID",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Iran",
        code: "+98",
        flag: "🇮🇷",
        iso: "IRN",
        iso_code: "IR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Iraq",
        code: "+964",
        flag: "🇮🇶",
        iso: "IRQ",
        iso_code: "IQ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Ireland",
        code: "+353",
        flag: "🇮🇪",
        iso: "IRL",
        iso_code: "IE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Israel",
        code: "+972",
        flag: "🇮🇱",
        iso: "ISR",
        iso_code: "IL",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Italy",
        code: "+39",
        flag: "🇮🇹",
        iso: "ITA",
        iso_code: "IT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Jamaica",
        code: "+1-876",
        flag: "🇯🇲",
        iso: "JAM",
        iso_code: "JM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Japan",
        code: "+81",
        flag: "🇯🇵",
        iso: "JPN",
        iso_code: "JP",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Jordan",
        code: "+962",
        flag: "🇯🇴",
        iso: "JOR",
        iso_code: "JO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Kazakhstan",
        code: "+7",
        flag: "🇰🇿",
        iso: "KAZ",
        iso_code: "KZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Kenya",
        code: "+254",
        flag: "🇰🇪",
        iso: "KEN",
        iso_code: "KE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Kiribati",
        code: "+686",
        flag: "🇰🇮",
        iso: "KIR",
        iso_code: "KI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Kosovo",
        code: "+383",
        flag: "🇽🇰",
        iso: "XKX",
        iso_code: "XK",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Kuwait",
        code: "+965",
        flag: "🇰🇼",
        iso: "KWT",
        iso_code: "KW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Kyrgyzstan",
        code: "+996",
        flag: "🇰🇬",
        iso: "KGZ",
        iso_code: "KG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Laos",
        code: "+856",
        flag: "🇱🇦",
        iso: "LAO",
        iso_code: "LO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Latvia",
        code: "+371",
        flag: "🇱🇻",
        iso: "LVA",
        iso_code: "LV",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Lebanon",
        code: "+961",
        flag: "🇱🇧",
        iso: "LBN",
        iso_code: "LB",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Lesotho",
        code: "+266",
        flag: "🇱🇸",
        iso: "LSO",
        iso_code: "LS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Liberia",
        code: "+231",
        flag: "🇱🇷",
        iso: "LBR",
        iso_code: "LR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Libya",
        code: "+218",
        flag: "🇱🇾",
        iso: "LBY",
        iso_code: "LY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Liechtenstein",
        code: "+423",
        flag: "🇱🇮",
        iso: "LIE",
        iso_code: "LI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Lithuania",
        code: "+370",
        flag: "🇱🇹",
        iso: "LTU",
        iso_code: "LT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Luxembourg",
        code: "+352",
        flag: "🇱🇺",
        iso: "LUX",
        iso_code: "LU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Madagascar",
        code: "+261",
        flag: "🇲🇬",
        iso: "MDG",
        iso_code: "MG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Malawi",
        code: "+265",
        flag: "🇲🇼",
        iso: "MWI",
        iso_code: "MW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Malaysia",
        code: "+60",
        flag: "🇲🇾",
        iso: "MYS",
        iso_code: "MY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Maldives",
        code: "+960",
        flag: "🇲🇻",
        iso: "MDV",
        iso_code: "MV",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Mali",
        code: "+223",
        flag: "🇲🇱",
        iso: "MLI",
        iso_code: "ML",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Malta",
        code: "+356",
        flag: "🇲🇹",
        iso: "MLT",
        iso_code: "MT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Marshall Islands",
        code: "+692",
        flag: "🇲🇭",
        iso: "MHL",
        iso_code: "MH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Mauritania",
        code: "+222",
        flag: "🇲🇷",
        iso: "MRT",
        iso_code: "MR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Mauritius",
        code: "+230",
        flag: "🇲🇺",
        iso: "MUS",
        iso_code: "MU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Mexico",
        code: "+52",
        flag: "🇲🇽",
        iso: "MEX",
        iso_code: "MX",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Micronesia",
        code: "+691",
        flag: "🇫🇲",
        iso: "FSM",
        iso_code: "FM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Moldova",
        code: "+373",
        flag: "🇲🇩",
        iso: "MDA",
        iso_code: "MD",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Monaco",
        code: "+377",
        flag: "🇲🇨",
        iso: "MCO",
        iso_code: "MC",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Mongolia",
        code: "+976",
        flag: "🇲🇳",
        iso: "MNG",
        iso_code: "MN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Montenegro",
        code: "+382",
        flag: "🇲🇪",
        iso: "MNE",
        iso_code: "ME",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Morocco",
        code: "+212",
        flag: "🇲🇦",
        iso: "MAR",
        iso_code: "MA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Mozambique",
        code: "+258",
        flag: "🇲🇿",
        iso: "MOZ",
        iso_code: "MZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Myanmar (Burma)",
        code: "+95",
        flag: "🇲🇲",
        iso: "MMR",
        iso_code: "MM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Namibia",
        code: "+264",
        flag: "🇳🇦",
        iso: "NAM",
        iso_code: "NA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Nauru",
        code: "+674",
        flag: "🇳🇷",
        iso: "NRU",
        iso_code: "NR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Nepal",
        code: "+977",
        flag: "🇳🇵",
        iso: "NPL",
        iso_code: "NP",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Netherlands",
        code: "+31",
        flag: "🇳🇱",
        iso: "NLD",
        iso_code: "NL",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "New Zealand",
        code: "+64",
        flag: "🇳🇿",
        iso: "NZL",
        iso_code: "NZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Nicaragua",
        code: "+505",
        flag: "🇳🇮",
        iso: "NIC",
        iso_code: "NI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Niger",
        code: "+227",
        flag: "🇳🇪",
        iso: "NER",
        iso_code: "NE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Nigeria",
        code: "+234",
        flag: "🇳🇬",
        iso: "NGA",
        iso_code: "NG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "North Korea",
        code: "+850",
        flag: "🇰🇵",
        iso: "PRK",
        iso_code: "KP",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "North Macedonia",
        code: "+389",
        flag: "🇲🇰",
        iso: "MKD",
        iso_code: "MK",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Norway",
        code: "+47",
        flag: "🇳🇴",
        iso: "NOR",
        iso_code: "NO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Oman",
        code: "+968",
        flag: "🇴🇲",
        iso: "OMN",
        iso_code: "OM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Pakistan",
        code: "+92",
        flag: "🇵🇰",
        iso: "PAK",
        iso_code: "",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Palau",
        code: "+680",
        flag: "🇵🇼",
        iso: "PLW",
        iso_code: "PW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Palestine",
        code: "+970",
        flag: "🇵🇸",
        iso: "PSE",
        iso_code: "PS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Panama",
        code: "+507",
        flag: "🇵🇦",
        iso: "PAN",
        iso_code: "PA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Papua New Guinea",
        code: "+675",
        flag: "🇵🇬",
        iso: "PNG",
        iso_code: "PG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Paraguay",
        code: "+595",
        flag: "🇵🇾",
        iso: "PRY",
        iso_code: "PY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Peru",
        code: "+51",
        flag: "🇵🇪",
        iso: "PER",
        iso_code: "PE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Philippines",
        code: "+63",
        flag: "🇵🇭",
        iso: "PHL",
        iso_code: "PH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Poland",
        code: "+48",
        flag: "🇵🇱",
        iso: "POL",
        iso_code: "PL",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Portugal",
        code: "+351",
        flag: "🇵🇹",
        iso: "PRT",
        iso_code: "PT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Qatar",
        code: "+974",
        flag: "🇶🇦",
        iso: "QAT",
        iso_code: "QA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Romania",
        code: "+40",
        flag: "🇷🇴",
        iso: "ROU",
        iso_code: "RO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Russia",
        code: "+7",
        flag: "🇷🇺",
        iso: "RUS",
        iso_code: "RU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Rwanda",
        code: "+250",
        flag: "🇷🇼",
        iso: "RWA",
        iso_code: "RW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Saint Kitts and Nevis",
        code: "+1-869",
        flag: "🇰🇳",
        iso: "KNA",
        iso_code: "KN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
// ModelCountry(name: "Saint Lucia", code: "+1-758", flag: "🇱🇨", iso: "LCA", iso_code: "LC"),
    ModelCountry(
        name: "St. Vincent & Grenadines",
        code: "+1-784",
        flag: "🇻🇨",
        iso: "VCT",
        iso_code: "VC",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Samoa",
        code: "+685",
        flag: "🇼🇸",
        iso: "WSM",
        iso_code: "WS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "San Marino",
        code: "+378",
        flag: "🇸🇲",
        iso: "SMR",
        iso_code: "SM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Sao Tome and Principe",
        code: "+239",
        flag: "🇸🇹",
        iso: "STP",
        iso_code: "ST",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Saudi Arabia",
        code: "+966",
        flag: "🇸🇦",
        iso: "SAU",
        iso_code: "SA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Senegal",
        code: "+221",
        flag: "🇸🇳",
        iso: "SEN",
        iso_code: "SN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Serbia",
        code: "+381",
        flag: "🇷🇸",
        iso: "SRB",
        iso_code: "RS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Seychelles",
        code: "+248",
        flag: "🇸🇨",
        iso: "SYC",
        iso_code: "SC",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Sierra Leone",
        code: "+232",
        flag: "🇸🇱",
        iso: "SLE",
        iso_code: "SL",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Singapore",
        code: "+65",
        flag: "🇸🇬",
        iso: "SGP",
        iso_code: "SG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Slovakia",
        code: "+421",
        flag: "🇸🇰",
        iso: "SVK",
        iso_code: "SK",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Slovenia",
        code: "+386",
        flag: "🇸🇮",
        iso: "SVN",
        iso_code: "SI",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Solomon Islands",
        code: "+677",
        flag: "🇸🇧",
        iso: "SLB",
        iso_code: "SB",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Somalia",
        code: "+252",
        flag: "🇸🇴",
        iso: "SOM",
        iso_code: "SO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "South Africa",
        code: "+27",
        flag: "🇿🇦",
        iso: "ZAF",
        iso_code: "ZA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "South Korea",
        code: "+82",
        flag: "🇰🇷",
        iso: "KOR",
        iso_code: "KO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Spain",
        code: "+34",
        flag: "🇪🇸",
        iso: "ESP",
        iso_code: "ES",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Sri Lanka",
        code: "+94",
        flag: "🇱🇰",
        iso: "LKA",
        iso_code: "LK",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Sudan",
        code: "+249",
        flag: "🇸🇩",
        iso: "SDN",
        iso_code: "SD",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "South Sudan",
        code: "+211",
        flag: "🇸🇸",
        iso: "SSD",
        iso_code: "SS",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Suriname",
        code: "+597",
        flag: "🇸🇷",
        iso: "SUR",
        iso_code: "SR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Sweden",
        code: "+46",
        flag: "🇸🇪",
        iso: "SWE",
        iso_code: "SE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Switzerland",
        code: "+41",
        flag: "🇨🇭",
        iso: "CHE",
        iso_code: "CH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Syria",
        code: "+963",
        flag: "🇸🇾",
        iso: "SYR",
        iso_code: "SY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Taiwan",
        code: "+886",
        flag: "🇹🇼",
        iso: "TWN",
        iso_code: "TW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Tajikistan",
        code: "+992",
        flag: "🇹🇯",
        iso: "TJK",
        iso_code: "TJ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Tanzania",
        code: "+255",
        flag: "🇹🇿",
        iso: "TZA",
        iso_code: "TZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Thailand",
        code: "+66",
        flag: "🇹🇭",
        iso: "THA",
        iso_code: "TH",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Togo",
        code: "+228",
        flag: "🇹🇬",
        iso: "TGO",
        iso_code: "TG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Tonga",
        code: "+676",
        flag: "🇹🇴",
        iso: "TON",
        iso_code: "TO",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Trinidad & Tobago",
        code: "+1-868",
        flag: "🇹🇹",
        iso: "TTO",
        iso_code: "TT",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Tunisia",
        code: "+216",
        flag: "🇹🇳",
        iso: "TUN",
        iso_code: "TN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Turkey",
        code: "+90",
        flag: "🇹🇷",
        iso: "TUR",
        iso_code: "TR",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Turkmenistan",
        code: "+993",
        flag: "🇹🇲",
        iso: "TKM",
        iso_code: "TM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Tuvalu",
        code: "+688",
        flag: "🇹🇻",
        iso: "TUV",
        iso_code: "TV",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Uganda",
        code: "+256",
        flag: "🇺🇬",
        iso: "UGA",
        iso_code: "UG",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Ukraine",
        code: "+380",
        flag: "🇺🇦",
        iso: "UKR",
        iso_code: "UA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "United Arab Emirates",
        code: "+971",
        flag: "🇦🇪",
        iso: "ARE",
        iso_code: "AE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "United Kingdom",
        code: "+44",
        flag: "🇬🇧",
        iso: "GBR",
        iso_code: "GB",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "United States",
        code: "+1",
        flag: "🇺🇸",
        iso: "USA",
        iso_code: "US",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Uruguay",
        code: "+598",
        flag: "🇺🇾",
        iso: "URY",
        iso_code: "UY",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Uzbekistan",
        code: "+998",
        flag: "🇺🇿",
        iso: "UZB",
        iso_code: "UZ",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Vanuatu",
        code: "+678",
        flag: "🇻🇺",
        iso: "VUT",
        iso_code: "VU",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Vatican City",
        code: "+379",
        flag: "🇻🇦",
        iso: "VAT",
        iso_code: "VA",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Venezuela",
        code: "+58",
        flag: "🇻🇪",
        iso: "VEN",
        iso_code: "VE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Vietnam",
        code: "+84",
        flag: "🇻🇳",
        iso: "VNM",
        iso_code: "VN",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Yemen",
        code: "+967",
        flag: "🇾🇪",
        iso: "YEM",
        iso_code: "YE",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Zambia",
        code: "+260",
        flag: "🇿🇲",
        iso: "ZMB",
        iso_code: "ZM",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
    ModelCountry(
        name: "Zimbabwe",
        code: "+263",
        flag: "🇿🇼",
        iso: "ZWE",
        iso_code: "ZW",
        currency: "pkr",
        currency_symbol: "Rs.",
        time_zone: "Asia/Karachi",
        latitude: 33.6844,
        longitude: 73.0479),
  ];
}

/*

ModelCountry(
name: "Afghanistan",
code: "+93",
flag: "🇦🇫",
iso: "AFG",
iso_code: "AF"),
ModelCountry(
name: "Albania",
code: "+355",
flag: "🇦🇱",
iso: "ALB",
iso_code: "AL"),
ModelCountry(
name: "Algeria",
code: "+213",
flag: "🇩🇿",
iso: "DZA",
iso_code: "DZ"),
ModelCountry(
name: "Andorra",
code: "+376",
flag: "🇦🇩",
iso: "AND",
iso_code: "AD"),
ModelCountry(
name: "Antarctica",
code: "+672",
flag: "🇦🇶",
iso: "ATA",
iso_code: "AQ"),
ModelCountry(
name: "Angola", code: "+244", flag: "🇦🇴", iso: "AGO", iso_code: "AO"),
ModelCountry(
name: "Anguilla",
code: "+1-264",
flag: "🇦🇮",
iso: "AIA",
iso_code: "AI"),
ModelCountry(
name: "Antigua and Barbuda",
code: "+1-268",
flag: "🇦🇬",
iso: "ATG",
iso_code: "AG"),
ModelCountry(
name: "Argentina",
code: "+54",
flag: "🇦🇷",
iso: "ARG",
iso_code: "AR"),
ModelCountry(
name: "Armenia",
code: "+374",
flag: "🇦🇲",
iso: "ARM",
iso_code: "AM"),
ModelCountry(
name: "Aruba", code: "+297", flag: "🇦🇼", iso: "ABW", iso_code: "AW"),
ModelCountry(
name: "Australia",
code: "+61",
flag: "🇦🇺",
iso: "AUS",
iso_code: "AU"),
ModelCountry(
name: "Austria", code: "+43", flag: "🇦🇹", iso: "AUT", iso_code: "AT"),
ModelCountry(
name: "Azerbaijan ",
code: "+994",
flag: "🇦🇿",
iso: "AZE",
iso_code: "AZ"),
ModelCountry(
name: "Bahamas",
code: "+1-242",
flag: "🇧🇸",
iso: "BHS",
iso_code: "BS"),
ModelCountry(
name: "Bahrain",
code: "+973",
flag: "🇧🇭",
iso: "BHR",
iso_code: "BH"),
ModelCountry(
name: "Bangladesh",
code: "+880",
flag: "🇧🇩",
iso: "BGD",
iso_code: "BD"),
ModelCountry(
name: "Barbados",
code: "+1-246",
flag: "🇧🇧",
iso: "BRB",
iso_code: "BB"),
ModelCountry(
name: "Belarus",
code: "+375",
flag: "🇧🇾",
iso: "BLR",
iso_code: "BY"),
ModelCountry(
name: "Belgium", code: "+32", flag: "🇧🇪", iso: "BEL", iso_code: "BE"),
ModelCountry(
name: "Belize", code: "+501", flag: "🇧🇿", iso: "BLZ", iso_code: "BZ"),
ModelCountry(
name: "Benin", code: "+229", flag: "🇧🇯", iso: "BEN", iso_code: "BJ"),
ModelCountry(
name: "Bhutan", code: "+975", flag: "🇧🇹", iso: "BTN", iso_code: "BT"),
ModelCountry(
name: "Bolivia",
code: "+591",
flag: "🇧🇴",
iso: "BOL",
iso_code: "BO"),
ModelCountry(
name: "Bosnia and Herzegovina",
code: "+387",
flag: "🇧🇦",
iso: "BIH",
iso_code: "BA"),
ModelCountry(
name: "Botswana",
code: "+267",
flag: "🇧🇼",
iso: "BWA",
iso_code: "BW"),
ModelCountry(
name: "Brazil", code: "+55", flag: "🇧🇷", iso: "BRA", iso_code: "BR"),
ModelCountry(
name: "Brunei", code: "+673", flag: "🇧🇳", iso: "BRN", iso_code: "BN"),
ModelCountry(
name: "Bulgaria",
code: "+359",
flag: "🇧🇬",
iso: "BGR",
iso_code: "BG"),
ModelCountry(
name: "Burkina Faso",
code: "+226",
flag: "🇧🇫",
iso: "BFA",
iso_code: "BF"),
ModelCountry(
name: "Burundi ",
code: "+257",
flag: "🇧🇮",
iso: "BDI",
iso_code: "BI"),
ModelCountry(
name: "Cape Verde",
code: "+238",
flag: "🇨🇻",
iso: "CPV",
iso_code: "CV"),
ModelCountry(
name: "Cambodia",
code: "+855",
flag: "🇰🇭",
iso: "KHM",
iso_code: "KH"),
ModelCountry(
name: "Cameroon",
code: "+237",
flag: "🇨🇲",
iso: "CMR",
iso_code: "CM"),
ModelCountry(
name: "Canada", code: "+1", flag: "🇨🇦", iso: "CAN", iso_code: "CA"),
ModelCountry(
name: "Central African Republic",
code: "+236",
flag: "🇨🇫",
iso: "CAF",
iso_code: "CF"),
ModelCountry(
name: "Chad", code: "+235", flag: "🇹🇩", iso: "TCD", iso_code: "TD"),
ModelCountry(
name: "Chile", code: "+56", flag: "🇨🇱", iso: "CHL", iso_code: "CL"),
ModelCountry(
name: "China", code: "+86", flag: "🇨🇳", iso: "CHN", iso_code: "CN"),
ModelCountry(
name: "Colombia",
code: "+57",
flag: "🇨🇴",
iso: "COL",
iso_code: "CO"),
ModelCountry(
name: "Comoros",
code: "+269",
flag: "🇰🇲",
iso: "COM",
iso_code: "KM"),
ModelCountry(
name: "Congo", code: "+242", flag: "🇨🇬", iso: "COG", iso_code: "CG"),
ModelCountry(
name: "Costa Rica",
code: "+506",
flag: "🇨🇷",
iso: "CRI",
iso_code: "CR"),
ModelCountry(
name: "Côte d’Ivoire",
code: "+225",
flag: "🇨🇮",
iso: "CIV",
iso_code: "CI"),
ModelCountry(
name: "Croatia",
code: "+385",
flag: "🇭🇷",
iso: "HRV",
iso_code: "HR"),
ModelCountry(
name: "Cuba", code: "+53", flag: "🇨🇺", iso: "CUB", iso_code: "CU"),
ModelCountry(
name: "Cyprus", code: "+357", flag: "🇨🇾", iso: "CYP", iso_code: "CY"),
ModelCountry(
name: "Denmark", code: "+45", flag: "🇩🇰", iso: "DNK", iso_code: "DK"),
ModelCountry(
name: "Djibouti",
code: "+253",
flag: "🇩🇯",
iso: "DJI",
iso_code: "DJ"),
ModelCountry(
name: "Dominica",
code: "+1-767",
flag: "🇩🇲",
iso: "DMA",
iso_code: "DM"),
ModelCountry(
name: "Dominican Republic ",
code: "+1-809, 1-829, 1-849",
flag: "🇩🇴",
iso: "DOM",
iso_code: "DO"),
ModelCountry(
name: "Ecuador",
code: "+593",
flag: "🇪🇨",
iso: "ECU",
iso_code: "EC"),
ModelCountry(
name: "Egypt", code: "+20", flag: "🇪🇬", iso: "EGY", iso_code: "EG"),
ModelCountry(
name: "El Salvador",
code: "+503",
flag: "🇸🇻",
iso: "SLV",
iso_code: "SV"),
ModelCountry(
name: "Equatorial Guinea",
code: "+240",
flag: "🇬🇶",
iso: "GNQ",
iso_code: "GQ"),
ModelCountry(
name: "Eritrea",
code: "+291",
flag: "🇪🇷",
iso: "ERI",
iso_code: "ER"),
ModelCountry(
name: "Estonia",
code: "+372",
flag: "🇪🇪",
iso: "EST",
iso_code: "EE"),
ModelCountry(
name: "Eswatini",
code: "+268",
flag: "🇸🇿",
iso: "SWZ",
iso_code: "SZ"),
ModelCountry(
name: "Ethiopia ",
code: "+251",
flag: "🇪🇹",
iso: "ETH",
iso_code: "ET"),
ModelCountry(
name: "Fiji", code: "+679", flag: "🇫🇯", iso: "FJI", iso_code: "FJ"),
ModelCountry(
name: "Finland",
code: "+358",
flag: "🇫🇮",
iso: "FIN",
iso_code: "FI"),
ModelCountry(
name: "France ", code: "+33", flag: "🇫🇷", iso: "FRA", iso_code: "FR"),
ModelCountry(
name: "Gabon", code: "+241", flag: "🇬🇦", iso: "GAB", iso_code: "GA"),
ModelCountry(
name: "Gambia", code: "+220", flag: "🇬🇲", iso: "GMB", iso_code: "GM"),
ModelCountry(
name: "Georgia",
code: "+995",
flag: "🇬🇪",
iso: "GEO",
iso_code: "GE"),
ModelCountry(
name: "Germany", code: "+49", flag: "🇩🇪", iso: "DEU", iso_code: "DE"),
ModelCountry(
name: "Ghana", code: "+233", flag: "🇬🇭", iso: "GHA", iso_code: "GH"),
ModelCountry(
name: "Greece", code: "+30", flag: "🇬🇷", iso: "GRC", iso_code: "GR"),
ModelCountry(
name: "Grenada",
code: "+1-473",
flag: "🇬🇩",
iso: "GRD",
iso_code: "GD"),
ModelCountry(
name: "Guatemala",
code: "+502",
flag: "🇬🇹",
iso: "GTM",
iso_code: "GT"),
ModelCountry(
name: "Guinea", code: "+224", flag: "🇬🇳", iso: "GIN", iso_code: "GN"),
ModelCountry(
name: "Guinea-Bissau",
code: "+245",
flag: "🇬🇼",
iso: "GNB",
iso_code: "GW"),
ModelCountry(
name: "Guyana", code: "+592", flag: "🇬🇾", iso: "GUY", iso_code: "GY"),
ModelCountry(
name: "Haiti", code: "+509", flag: "🇭🇹", iso: "HTI", iso_code: "HT"),
ModelCountry(
name: "Honduras",
code: "+504",
flag: "🇭🇳",
iso: "HND",
iso_code: "HN"),
ModelCountry(
name: "Hungary", code: "+36", flag: "🇭🇺", iso: "HUN", iso_code: "HU"),
ModelCountry(
name: "Iceland",
code: "+354",
flag: "🇮🇸",
iso: "ISL",
iso_code: "IS"),
ModelCountry(
name: "India", code: "+91", flag: "🇮🇳", iso: "IND", iso_code: "IN"),
ModelCountry(
name: "Indonesia",
code: "+62",
flag: "🇮🇩",
iso: "IDN",
iso_code: "ID"),
ModelCountry(
name: "Iran", code: "+98", flag: "🇮🇷", iso: "IRN", iso_code: "IR"),
ModelCountry(
name: "Iraq", code: "+964", flag: "🇮🇶", iso: "IRQ", iso_code: "IQ"),
ModelCountry(
name: "Ireland",
code: "+353",
flag: "🇮🇪",
iso: "IRL",
iso_code: "IE"),
// ModelCountry(name: "Israel", code: "+972", flag: "🇮🇱", iso: "ISR", iso_code: "IL"),
ModelCountry(
name: "Italy", code: "+39", flag: "🇮🇹", iso: "ITA", iso_code: "IT"),
ModelCountry(
name: "Jamaica",
code: "+1-876",
flag: "🇯🇲",
iso: "JAM",
iso_code: "JM"),
ModelCountry(
name: "Japan", code: "+81", flag: "🇯🇵", iso: "JPN", iso_code: "JP"),
ModelCountry(
name: "Jordan", code: "+962", flag: "🇯🇴", iso: "JOR", iso_code: "JO"),
ModelCountry(
name: "Kazakhstan",
code: "+7",
flag: "🇰🇿",
iso: "KAZ",
iso_code: "KZ"),
ModelCountry(
name: "Kenya", code: "+254", flag: "🇰🇪", iso: "KEN", iso_code: "KE"),
ModelCountry(
name: "Kiribati",
code: "+686",
flag: "🇰🇮",
iso: "KIR",
iso_code: "KI"),
ModelCountry(
name: "Kosovo", code: "+383", flag: "🇽🇰", iso: "XKX", iso_code: "XK"),
ModelCountry(
name: "Kuwait", code: "+965", flag: "🇰🇼", iso: "KWT", iso_code: "KW"),
ModelCountry(
name: "Kyrgyzstan",
code: "+996",
flag: "🇰🇬",
iso: "KGZ",
iso_code: "KG"),
ModelCountry(
name: "Laos", code: "+856", flag: "🇱🇦", iso: "LAO", iso_code: "LO"),
ModelCountry(
name: "Latvia", code: "+371", flag: "🇱🇻", iso: "LVA", iso_code: "LV"),
ModelCountry(
name: "Lebanon",
code: "+961",
flag: "🇱🇧",
iso: "LBN",
iso_code: "LB"),
ModelCountry(
name: "Lesotho",
code: "+266",
flag: "🇱🇸",
iso: "LSO",
iso_code: "LS"),
ModelCountry(
name: "Liberia",
code: "+231",
flag: "🇱🇷",
iso: "LBR",
iso_code: "LR"),
ModelCountry(
name: "Libya", code: "+218", flag: "🇱🇾", iso: "LBY", iso_code: "LY"),
ModelCountry(
name: "Liechtenstein",
code: "+423",
flag: "🇱🇮",
iso: "LIE",
iso_code: "LI"),
ModelCountry(
name: "Lithuania",
code: "+370",
flag: "🇱🇹",
iso: "LTU",
iso_code: "LT"),
ModelCountry(
name: "Luxembourg",
code: "+352",
flag: "🇱🇺",
iso: "LUX",
iso_code: "LU"),
ModelCountry(
name: "Madagascar",
code: "+261",
flag: "🇲🇬",
iso: "MDG",
iso_code: "MG"),
ModelCountry(
name: "Malawi", code: "+265", flag: "🇲🇼", iso: "MWI", iso_code: "MW"),
ModelCountry(
name: "Malaysia",
code: "+60",
flag: "🇲🇾",
iso: "MYS",
iso_code: "MY"),
ModelCountry(
name: "Maldives",
code: "+960",
flag: "🇲🇻",
iso: "MDV",
iso_code: "MV"),
ModelCountry(
name: "Mali", code: "+223", flag: "🇲🇱", iso: "MLI", iso_code: "ML"),
ModelCountry(
name: "Malta", code: "+356", flag: "🇲🇹", iso: "MLT", iso_code: "MT"),
ModelCountry(
name: "Marshall Islands",
code: "+692",
flag: "🇲🇭",
iso: "MHL",
iso_code: "MH"),
ModelCountry(
name: "Mauritania",
code: "+222",
flag: "🇲🇷",
iso: "MRT",
iso_code: "MR"),
ModelCountry(
name: "Mauritius",
code: "+230",
flag: "🇲🇺",
iso: "MUS",
iso_code: "MU"),
ModelCountry(
name: "Mexico", code: "+52", flag: "🇲🇽", iso: "MEX", iso_code: "MX"),
ModelCountry(
name: "Micronesia",
code: "+691",
flag: "🇫🇲",
iso: "FSM",
iso_code: "FM"),
ModelCountry(
name: "Moldova",
code: "+373",
flag: "🇲🇩",
iso: "MDA",
iso_code: "MD"),
ModelCountry(
name: "Monaco", code: "+377", flag: "🇲🇨", iso: "MCO", iso_code: "MC"),
ModelCountry(
name: "Mongolia",
code: "+976",
flag: "🇲🇳",
iso: "MNG",
iso_code: "MN"),
ModelCountry(
name: "Montenegro",
code: "+382",
flag: "🇲🇪",
iso: "MNE",
iso_code: "ME"),
ModelCountry(
name: "Morocco",
code: "+212",
flag: "🇲🇦",
iso: "MAR",
iso_code: "MA"),
ModelCountry(
name: "Mozambique",
code: "+258",
flag: "🇲🇿",
iso: "MOZ",
iso_code: "MZ"),
ModelCountry(
name: "Myanmar (Burma)",
code: "+95",
flag: "🇲🇲",
iso: "MMR",
iso_code: "MM"),
ModelCountry(
name: "Namibia",
code: "+264",
flag: "🇳🇦",
iso: "NAM",
iso_code: "NA"),
ModelCountry(
name: "Nauru", code: "+674", flag: "🇳🇷", iso: "NRU", iso_code: "NR"),
ModelCountry(
name: "Nepal", code: "+977", flag: "🇳🇵", iso: "NPL", iso_code: "NP"),
ModelCountry(
name: "Netherlands",
code: "+31",
flag: "🇳🇱",
iso: "NLD",
iso_code: "NL"),
ModelCountry(
name: "New Zealand",
code: "+64",
flag: "🇳🇿",
iso: "NZL",
iso_code: "NZ"),
ModelCountry(
name: "Nicaragua",
code: "+505",
flag: "🇳🇮",
iso: "NIC",
iso_code: "NI"),
ModelCountry(
name: "Niger", code: "+227", flag: "🇳🇪", iso: "NER", iso_code: "NE"),
ModelCountry(
name: "Nigeria",
code: "+234",
flag: "🇳🇬",
iso: "NGA",
iso_code: "NG"),
ModelCountry(
name: "North Korea",
code: "+850",
flag: "🇰🇵",
iso: "PRK",
iso_code: "KP"),
ModelCountry(
name: "North Macedonia",
code: "+389",
flag: "🇲🇰",
iso: "MKD",
iso_code: "MK"),
ModelCountry(
name: "Norway", code: "+47", flag: "🇳🇴", iso: "NOR", iso_code: "NO"),
ModelCountry(
name: "Oman", code: "+968", flag: "🇴🇲", iso: "OMN", iso_code: "OM"),
ModelCountry(
name: "Pakistan", code: "+92", flag: "🇵🇰", iso: "PAK", iso_code: ""),
ModelCountry(
name: "Palau", code: "+680", flag: "🇵🇼", iso: "PLW", iso_code: "PW"),
ModelCountry(
name: "Palestine",
code: "+970",
flag: "🇵🇸",
iso: "PSE",
iso_code: "PS"),
ModelCountry(
name: "Panama", code: "+507", flag: "🇵🇦", iso: "PAN", iso_code: "PA"),
ModelCountry(
name: "Papua New Guinea",
code: "+675",
flag: "🇵🇬",
iso: "PNG",
iso_code: "PG"),
ModelCountry(
name: "Paraguay",
code: "+595",
flag: "🇵🇾",
iso: "PRY",
iso_code: "PY"),
ModelCountry(
name: "Peru", code: "+51", flag: "🇵🇪", iso: "PER", iso_code: "PE"),
ModelCountry(
name: "Philippines",
code: "+63",
flag: "🇵🇭",
iso: "PHL",
iso_code: "PH"),
ModelCountry(
name: "Poland", code: "+48", flag: "🇵🇱", iso: "POL", iso_code: "PL"),
ModelCountry(
name: "Portugal",
code: "+351",
flag: "🇵🇹",
iso: "PRT",
iso_code: "PT"),
ModelCountry(
name: "Qatar", code: "+974", flag: "🇶🇦", iso: "QAT", iso_code: "QA"),
ModelCountry(
name: "Romania", code: "+40", flag: "🇷🇴", iso: "ROU", iso_code: "RO"),
ModelCountry(
name: "Russia", code: "+7", flag: "🇷🇺", iso: "RUS", iso_code: "RU"),
ModelCountry(
name: "Rwanda", code: "+250", flag: "🇷🇼", iso: "RWA", iso_code: "RW"),
ModelCountry(
name: "Saint Kitts and Nevis",
code: "+1-869",
flag: "🇰🇳",
iso: "KNA",
iso_code: "KN"),
// ModelCountry(name: "Saint Lucia", code: "+1-758", flag: "🇱🇨", iso: "LCA", iso_code: "LC"),
ModelCountry(
name: "St. Vincent & Grenadines",
code: "+1-784",
flag: "🇻🇨",
iso: "VCT",
iso_code: "VC"),
ModelCountry(
name: "Samoa", code: "+685", flag: "🇼🇸", iso: "WSM", iso_code: "WS"),
ModelCountry(
name: "San Marino",
code: "+378",
flag: "🇸🇲",
iso: "SMR",
iso_code: "SM"),
ModelCountry(
name: "Sao Tome and Principe",
code: "+239",
flag: "🇸🇹",
iso: "STP",
iso_code: "ST"),
ModelCountry(
name: "Saudi Arabia",
code: "+966",
flag: "🇸🇦",
iso: "SAU",
iso_code: "SA"),
ModelCountry(
name: "Senegal",
code: "+221",
flag: "🇸🇳",
iso: "SEN",
iso_code: "SN"),
ModelCountry(
name: "Serbia", code: "+381", flag: "🇷🇸", iso: "SRB", iso_code: "RS"),
ModelCountry(
name: "Seychelles",
code: "+248",
flag: "🇸🇨",
iso: "SYC",
iso_code: "SC"),
ModelCountry(
name: "Sierra Leone",
code: "+232",
flag: "🇸🇱",
iso: "SLE",
iso_code: "SL"),
ModelCountry(
name: "Singapore",
code: "+65",
flag: "🇸🇬",
iso: "SGP",
iso_code: "SG"),
ModelCountry(
name: "Slovakia",
code: "+421",
flag: "🇸🇰",
iso: "SVK",
iso_code: "SK"),
ModelCountry(
name: "Slovenia",
code: "+386",
flag: "🇸🇮",
iso: "SVN",
iso_code: "SI"),
ModelCountry(
name: "Solomon Islands",
code: "+677",
flag: "🇸🇧",
iso: "SLB",
iso_code: "SB"),
ModelCountry(
name: "Somalia",
code: "+252",
flag: "🇸🇴",
iso: "SOM",
iso_code: "SO"),
ModelCountry(
name: "South Africa",
code: "+27",
flag: "🇿🇦",
iso: "ZAF",
iso_code: "ZA"),
ModelCountry(
name: "South Korea",
code: "+82",
flag: "🇰🇷",
iso: "KOR",
iso_code: "KO"),
ModelCountry(
name: "Spain", code: "+34", flag: "🇪🇸", iso: "ESP", iso_code: "ES"),
ModelCountry(
name: "Sri Lanka",
code: "+94",
flag: "🇱🇰",
iso: "LKA",
iso_code: "LK"),
ModelCountry(
name: "Sudan", code: "+249", flag: "🇸🇩", iso: "SDN", iso_code: "SD"),
ModelCountry(
name: "South Sudan",
code: "+211",
flag: "🇸🇸",
iso: "SSD",
iso_code: "SS"),
ModelCountry(
name: "Suriname",
code: "+597",
flag: "🇸🇷",
iso: "SUR",
iso_code: "SR"),
ModelCountry(
name: "Sweden", code: "+46", flag: "🇸🇪", iso: "SWE", iso_code: "SE"),
ModelCountry(
name: "Switzerland",
code: "+41",
flag: "🇨🇭",
iso: "CHE",
iso_code: "CH"),
ModelCountry(
name: "Syria", code: "+963", flag: "🇸🇾", iso: "SYR", iso_code: "SY"),
ModelCountry(
name: "Taiwan", code: "+886", flag: "🇹🇼", iso: "TWN", iso_code: "TW"),
ModelCountry(
name: "Tajikistan",
code: "+992",
flag: "🇹🇯",
iso: "TJK",
iso_code: "TJ"),
ModelCountry(
name: "Tanzania",
code: "+255",
flag: "🇹🇿",
iso: "TZA",
iso_code: "TZ"),
ModelCountry(
name: "Thailand",
code: "+66",
flag: "🇹🇭",
iso: "THA",
iso_code: "TH"),
ModelCountry(
name: "Togo", code: "+228", flag: "🇹🇬", iso: "TGO", iso_code: "TG"),
ModelCountry(
name: "Tonga", code: "+676", flag: "🇹🇴", iso: "TON", iso_code: "TO"),
ModelCountry(
name: "Trinidad & Tobago",
code: "+1-868",
flag: "🇹🇹",
iso: "TTO",
iso_code: "TT"),
ModelCountry(
name: "Tunisia",
code: "+216",
flag: "🇹🇳",
iso: "TUN",
iso_code: "TN"),
ModelCountry(
name: "Turkey", code: "+90", flag: "🇹🇷", iso: "TUR", iso_code: "TR"),
ModelCountry(
name: "Turkmenistan",
code: "+993",
flag: "🇹🇲",
iso: "TKM",
iso_code: "TM"),
ModelCountry(
name: "Tuvalu", code: "+688", flag: "🇹🇻", iso: "TUV", iso_code: "TV"),
ModelCountry(
name: "Uganda", code: "+256", flag: "🇺🇬", iso: "UGA", iso_code: "UG"),
ModelCountry(
name: "Ukraine",
code: "+380",
flag: "🇺🇦",
iso: "UKR",
iso_code: "UA"),
ModelCountry(
name: "United Arab Emirates",
code: "+971",
flag: "🇦🇪",
iso: "ARE",
iso_code: "AE"),
ModelCountry(
name: "United Kingdom",
code: "+44",
flag: "🇬🇧",
iso: "GBR",
iso_code: "GB"),
ModelCountry(
name: "United States",
code: "+1",
flag: "🇺🇸",
iso: "USA",
iso_code: "US"),
ModelCountry(
name: "Uruguay",
code: "+598",
flag: "🇺🇾",
iso: "URY",
iso_code: "UY"),
ModelCountry(
name: "Uzbekistan",
code: "+998",
flag: "🇺🇿",
iso: "UZB",
iso_code: "UZ"),
ModelCountry(
name: "Vanuatu",
code: "+678",
flag: "🇻🇺",
iso: "VUT",
iso_code: "VU"),
ModelCountry(
name: "Vatican City",
code: "+379",
flag: "🇻🇦",
iso: "VAT",
iso_code: "VA"),
ModelCountry(
name: "Venezuela",
code: "+58",
flag: "🇻🇪",
iso: "VEN",
iso_code: "VE"),
ModelCountry(
name: "Vietnam", code: "+84", flag: "🇻🇳", iso: "VNM", iso_code: "VN"),
ModelCountry(
name: "Yemen", code: "+967", flag: "🇾🇪", iso: "YEM", iso_code: "YE"),
ModelCountry(
name: "Zambia", code: "+260", flag: "🇿🇲", iso: "ZMB", iso_code: "ZM"),
ModelCountry(
name: "Zimbabwe",
code: "+263",
flag: "🇿🇼",
iso: "ZWE",
iso_code: "ZW"),*/
